name: Deploy VPC
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup AWS CLi
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Deploy Stack
        id: deploy_stack
        run: | 
          aws cloudformation deploy --stack-name test --template-file test.yaml
      - name: Echo Stack Outputs
        run: |
          # Parse the output values and print them
          echo "Stack Outputs:"
          aws cloudformation describe-stacks --stack-name test --query "Stack[0].Outputs" --output text
